<a href="https://colab.research.google.com/github/0-lingual/Advanced-machine-learning/blob/main/tensorflow_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Requires the latest pip
!pip install --upgrade pip

# Current stable release for CPU and GPU
!pip install tensorflow

# Or try the preview build (unstable)
!pip install tf-nightly

!docker pull tensorflow/tensorflow:latest  # Download latest stable image
!docker run -it -p 8888:8888 tensorflow/tensorflow:latest-jupyter  # Start Jupyter server

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 9.3 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.4/585.4 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 66.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 40.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 50.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 58.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 19.7 MB/s eta 0:00:00
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Found existing installation: h5py

In [4]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0-dev20240429


In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.20165506,  0.29959205, -0.10996265,  0.04058358,  0.7892132 ,
        -0.13925645, -0.4390953 ,  0.07101769,  0.13063842, -0.18895854]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.07525635, 0.12423156, 0.08248303, 0.09588397, 0.20270838,
        0.08010183, 0.05935046, 0.09884696, 0.10491952, 0.07621793]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.5244565

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8586 - loss: 0.4785
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9565 - loss: 0.1493
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9684 - loss: 0.1050
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9730 - loss: 0.0860
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9779 - loss: 0.0700


In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9783 - loss: 0.0693


[0.06932701915502548, 0.9782999753952026]

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.33071499e-08, 2.60395350e-09, 1.11949430e-06, 1.26485436e-04,
        8.88111029e-10, 3.69745067e-07, 1.52266498e-11, 9.99863029e-01,
        8.05428442e-07, 8.19315756e-06],
       [2.03308481e-09, 1.82026168e-04, 9.99815404e-01, 3.48953336e-07,
        7.13746130e-15, 7.35916927e-08, 3.45618005e-08, 8.83756881e-13,
        2.09379800e-06, 2.48745642e-12],
       [9.39625266e-08, 9.98927295e-01, 7.39685347e-05, 1.27625108e-05,
        4.10822249e-05, 4.62452363e-06, 1.26799541e-05, 7.89547921e-04,
        1.35446462e-04, 2.55780469e-06],
       [9.98140097e-01, 2.47464893e-09, 4.93724383e-06, 8.19286470e-08,
        1.75654611e-06, 1.45104320e-06, 1.85110909e-03, 3.86853117e-07,
        1.05659295e-08, 1.65336033e-07],
       [1.72662385e-06, 6.68679778e-09, 8.67107076e-07, 4.48975328e-07,
        9.97520506e-01, 1.65525410e-06, 5.88363355e-06, 6.36343902e-05,
        4.09331932e-07, 2.40474171e-03]], dtype=float32)>

In [19]:
model.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9743 - loss: 0.0808


[0.06932701915502548, 0.9782999753952026]